### ISSUE TITLE
Configuring keys for `debugHeaders`

### ISSUE THREAD

**Issue by mfyodorov** [gravity-ui/gateway#50]
The `debugHeaders` are limited [set of fields](https://github.com/gravity-ui/gateway/blob/183cdd636648e845e3f874e3510eff4f243f219c/lib/components/rest.ts#L234-L245). It would be convenient to specify a custom set of headers keys, values of which would be added in the `debugHeaders`. 

For example, headers may contain some kind of traceId header (in the `@gravity-ui/nodekit` it is [uber-trace-id](https://github.com/gravity-ui/nodekit/blob/fe2d84137e53ef7c81972a5ede8283ba7a6b2dbb/src/lib/consts.ts#L4)) which supposed to be [logged](https://github.com/gravity-ui/gateway/blob/183cdd636648e845e3f874e3510eff4f243f219c/lib/components/rest.ts#L265) as one of `debugHeaders`. 

The logic for mapping can be reused from [proxyHeaders](https://github.com/gravity-ui/gateway/blob/183cdd636648e845e3f874e3510eff4f243f219c/lib/components/rest.ts#L175-L179).

**Comment by mfyodorov** [comment]
@SeqviriouM what do you think?

**Comment by SeqviriouM** [comment]
How do you see it? Separate configuration via option `proxyDebugHeaders`

**Comment by mfyodorov** [comment]
@SeqviriouM Yes, add [here](https://github.com/gravity-ui/gateway/blob/183cdd636648e845e3f874e3510eff4f243f219c/lib/components/rest.ts#L246) something like this:

```ts
// proxyDebugHeaders: string[]
for (const headerName of proxyDebugHeaders) {
    if (headers[headerName] !== undefined) {
        debugHeaders[headerName] = headers[headerName]; // or debugHeaders[`x-header-${headerName}`] = headers[headerName]
    }
}
```

**Comment by SeqviriouM** [comment]
@mfyodorov yeah, I think it will be useful to add this option

**Comment by SeqviriouM** [comment]
@mfyodorov I started the implementation and thought why we can't just normally send these headers (for example `uber-trace-id`) as response headers? Or it can be unique headers that we don't want to return to users?

The meaning of the `debugHeaders` was mainly to return the configuration from the gateway

**Comment by SeqviriouM** [comment]
@mfyodorov the functionality appeared in the version 2.4.0 (https://github.com/gravity-ui/gateway/blob/main/CHANGELOG.md#240-2024-04-17)
